spring:
  kafka:
    bootstrap-servers: localhost:9094
    template:
      default-topic: energy-usage
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  application:
    name: ingestion-service

server:
  port: 8082

simulation:
  endpoint: http://localhost:8082/api/v1/ingestion
  requests-per-interval: 10000
  interval-ms: 60000
  parallel-threads: 10

